---
appSettings:
  key1: "key1 for sample app, value coming from configserver repo"
systemweb:
  httpRuntime:
    targetFramework: "4.6.2"
connectionStrings:
  conn1: "conn1 coming from config repo"
---
